name: Dataset Update Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  update-dataset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          pip install dvc
          pip install -r requirements.txt
      - name: Execute data preprocessing
        run: python preprocess_data.py
      - name: Add new data to DVC
        run: |
          dvc add data/my_updated_data.csv
          git add data/my_updated_data.csv.dvc
          git commit -m "Updated dataset"
      - name: Push data to DVC remote storage
        run: dvc push
